apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: https://charts.bitnami.com/bitnami/wordpress-10.11.2.tgz
        digest: sha256:ee20c610b3fc5aa9f26d2c120412a254694217225d34ef3bd664344772639e56
        lastCertifiedTimestamp: "2021-05-11T14:11:41.240133+02:00"
        certifiedOpenShiftVersions: 4.7.5
    chart:
        name: wordpress
        home: https://github.com/bitnami/charts/tree/master/bitnami/wordpress
        sources:
          - https://github.com/bitnami/bitnami-docker-wordpress
          - https://wordpress.org/
        version: 10.11.2
        description: Web publishing platform for building blogs and websites.
        keywords:
          - application
          - blog
          - cms
          - http
          - php
          - web
          - wordpress
        maintainers:
          - name: Bitnami
            email: containers@bitnami.com
            url: ""
        icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 5.7.1
        deprecated: false
        annotations:
            category: CMS
        kubeversion: ""
        dependencies:
          - name: mariadb
            version: 9.x.x
            repository: https://charts.bitnami.com/bitnami
            condition: mariadb.enabled
            tags: []
            enabled: false
            importvalues: []
            alias: ""
          - name: memcached
            version: 5.x.x
            repository: https://charts.bitnami.com/bitnami
            condition: memcached.enabled
            tags: []
            enabled: false
            importvalues: []
            alias: ""
          - name: common
            version: 1.x.x
            repository: https://charts.bitnami.com/bitnami
            condition: ""
            tags:
              - bitnami-common
            enabled: false
            importvalues: []
            alias: ""
        type: ""
    overrides: ""
results:
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version is specified
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : docker.io/bitnami/wordpress:5.7.1-debian-10-r19 
        Image is Red Hat certified : docker.io/bitnami/mariadb:10.5.9-debian-10-r56 
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist

